name = "Ciao!"
description = "A beautiful and least dependency blog theme"
license = "MPL 2.0"
homepage = "https://github.com/Tsai002/nodep"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://tsai002.github.io/"

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "Tsai002"
homepage = "https://tsai002.github.io/"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "Nicole White"
homepage = "https://github.com/nicolewhite"
repo = "https://github.com/nicolewhite/nicolewhite.github.io_old"